# Generated by Django 5.2.4 on 2025-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_options_productimage_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
