# Generated by Django 5.2.4 on 2025-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='drops/'),
        ),
    ]
