# Generated by Django 5.2.4 on 2025-08-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_drop_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='drops/featured_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=True),
        ),
    ]
